// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkhhlgdvergclvkdejkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraGhsZ2R2ZXJnY2x2a2RlamtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDU1MzYsImV4cCI6MjA2NDI4MTUzNn0.Qc_RkX51k7MZeu16xVaenY3ogV9OSfOFxl1lR0kuBto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);